budget/urls.py
from django.conf.urls import patterns, url

from budget import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^date/(?P<month>\w+)/(?P<year>\d+)/$', views.index, name='index'),
    
    url(r'^alltransactions/$', views.alltransactions, name='alltransactions'),
    url(r'^transaction/(?P<tid>\d+)/(?P<aid>\d+)/$', views.transaction, name='transaction'),
    url(r'^addtransaction/(?P<to_account>\d+)/$', views.addtransaction, name='addtransaction'),
	url(r'^addtransactions/$', views.addtransactions, name='addtransactions'),
    url(r'^banktransaction/$', views.banktransaction, name='banktransaction'),
	url(r'^transaction/delete/(?P<tid>\d+)/$', views.transaction_delete, name='transactiondelete'),
    
    url(r'^account/(?P<aid>\d+)/$', views.account, name='account'),
    url(r'^account/(?P<aid>\d+)/subaccount/$', views.addsubaccount, name='addsubaccount'),
    url(r'^account/(?P<aid>\d+)/date/(?P<month>\w+)/(?P<year>\d+)/$', views.account, name='account'),
    url(r'^account/add/(?P<cid>\d+)/$', views.addaccount, name='addaccount'),
    url(r'^account/edit/(?P<aid>\d+)/$', views.editaccount, name='editaccount'),
    url(r'^account/delete/(?P<aid>\d+)/$', views.deleteaccount, name='deleteaccount'),
    
    url(r'^category/(?P<cid>\d+)/$', views.category, name='category'),
    
    ### AJAX URLS ###
    url(r'^projection/$', views.set_projection, name='set_projection'),
)

budgettracker/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'budgettracker.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^budget/', include('budget.urls', namespace="budget")),
    url(r'^admin/', include(admin.site.urls)),
)

budget/models.py
from django.db import models
from django.forms import ModelForm, extras

class AccountCategory(models.Model):
	name = models.CharField(max_length=30)
	income_accounts = models.NullBooleanField()
	goal_accounts = models.BooleanField(default=False)
	def __unicode__(self):
		return self.name
	
class Account(models.Model):
	name = models.CharField(max_length=200)
	balance = models.DecimalField(max_digits=8, decimal_places=2)
	category = models.ForeignKey(AccountCategory)
	goal = models.DecimalField(max_digits=8, decimal_places=2)
	goal_account = models.BooleanField(default=True)
	parent_account = models.ForeignKey('self', related_name="parent_account_", default=None, blank=True, null=True)
	def __unicode__(self):
		return self.name
	def is_income(self):
		return self.category.income_accounts
	def is_goal(self):
		return self.goal_account
	def is_bank(self):
		return self.category.income_accounts == None

class Transaction(models.Model):
	date = models.DateField()
	to_account = models.ForeignKey(Account, related_name="to_account")
	from_account = models.ForeignKey(Account, related_name="from_account")
	amount = models.DecimalField(max_digits=7, decimal_places=2)
	prediction = models.BooleanField()
	memo = models.CharField(max_length=300, default=None, blank=True, null=True)
	def __unicode__(self):
		return "$"+unicode(self.amount)+" : "+self.from_account.name+" -> "+self.to_account.name
                
class TransactionForm(ModelForm):
	class Meta:
		model = Transaction
		fields = ['date', 'amount', 'memo']
		widgets = {
			'date': extras.SelectDateWidget(years=['2013','2014','2015','2016']),
		}
                
class AddTransactionForm(ModelForm):
	class Meta:
		model = Transaction
		fields = ['date', 'from_account', 'amount', 'memo']
		widgets = {
			'date': extras.SelectDateWidget(years=['2013','2014','2015','2016']),
		}
	#http://stackoverflow.com/questions/962226/need-help-with-django-modelform-how-to-filter-foreignkey-manytomanyfield
	def __init__(self, *args, **kwargs):
		super(AddTransactionForm, self).__init__(*args, **kwargs)
		if self.instance:
			bank_category = AccountCategory.objects.get(name='Bank Accounts')
			self.fields['from_account'].queryset = Account.objects.filter(category=bank_category)

class NullAccountTransactionForm(ModelForm):
	class Meta:
		model = Transaction
		fields = ['date', 'from_account', 'to_account', 'amount', 'memo']
		widgets = {
			'date': extras.SelectDateWidget(),
		}
	#http://stackoverflow.com/questions/962226/need-help-with-django-modelform-how-to-filter-foreignkey-manytomanyfield
	def __init__(self, *args, **kwargs):
		super(NullAccountTransactionForm, self).__init__(*args, **kwargs)
		if self.instance:
			bank_category = AccountCategory.objects.get(name='Bank Accounts')
			self.fields['from_account'].queryset = Account.objects.filter(category=bank_category)
			self.fields['to_account'].queryset = Account.objects.filter(category=bank_category)

class AccountForm(ModelForm):
	class Meta:
		model = Account
		fields = ['name', 'balance', 'category', 'parent_account', 'goal', 'goal_account']
	#http://stackoverflow.com/questions/962226/need-help-with-django-modelform-how-to-filter-foreignkey-manytomanyfield
	def __init__(self, *args, **kwargs):
		super(AccountForm, self).__init__(*args, **kwargs)
		if self.instance:
			bank_category = AccountCategory.objects.get(name='Bank Accounts')
			self.fields['parent_account'].queryset = Account.objects.filter(category=bank_category).filter(parent_account=None)

class AddAccountForm(ModelForm):
	class Meta:
		model = Account
		fields = ['name']

budget/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
from decimal import Decimal
from django.core.serializers import serialize
from django.utils import simplejson as json

from budget.models import Transaction, Account, AccountCategory, TransactionForm, AddTransactionForm, NullAccountTransactionForm, AccountForm, AddAccountForm
import datetime

def month_abbr_to_int(month, previous_month):
	if month == 'Jan':
		return 12 if previous_month else 1
	if month == 'Feb':
		return 1 if previous_month else 2
	if month == 'Mar':
		return 2 if previous_month else 3
	if month == 'Apr':
		return 3 if previous_month else 4
	if month == 'May':
		return 4 if previous_month else 5
	if month == 'Jun':
		return 5 if previous_month else 6
	if month == 'Jul':
		return 6 if previous_month else 7
	if month == 'Aug':
		return 7 if previous_month else 8
	if month == 'Sep':
		return 8 if previous_month else 9
	if month == 'Oct':
		return 9 if previous_month else 10
	if month == 'Nov':
		return 10 if previous_month else 11
	if month == 'Dec':
		return 11 if previous_month else 12

def start_end_days_of_month(month_str, year_str):
	month = month_abbr_to_int(month_str, False)
	year = int(year_str)
	start_date = datetime.date(year, month, 1)
	if (month_str == 'Feb'):
		if year%4 == 0 and (year%100 != 0 or year%400 == 0):
			end_date = datetime.date(year, month, 29)
		else:
			end_date = datetime.date(year, month, 28)
	elif (month_str in ['Jan', 'Mar', 'May', 'Jul', 'Aug', 'Oct', 'Dec']):
		end_date = datetime.date(year, month, 31)
	else:
		end_date = datetime.date(year, month, 30)
	return [start_date, end_date]

def get_account_amounts_by_date(account_id, month_str, year_str):
	ret = {}
	
	dates = start_end_days_of_month(month_str, year_str)
	
	acct = Account.objects.get(pk=account_id)
	
	if (acct.category.income_accounts == None):
		deposits = Transaction.objects.filter(to_account=acct).filter(prediction=False).filter(date__range=(dates[0], dates[1]))
		withdrawals = Transaction.objects.filter(from_account=acct).filter(prediction=False).filter(date__range=(dates[0], dates[1]))
		balance = Decimal(0.0)
		for dep in deposits:
			balance += dep.amount
		for wit in withdrawals:
			balance -= wit.amount
		ret['actual'] = balance
	else:
		projections = Transaction.objects.filter(to_account=acct).filter(prediction=True).filter(date__range=(dates[0], dates[1]))
		if acct.is_income():
			actuals = Transaction.objects.filter(from_account=acct).filter(prediction=False).filter(date__range=(dates[0], dates[1]))
		else:
			actuals = Transaction.objects.filter(to_account=acct).filter(prediction=False).filter(date__range=(dates[0], dates[1]))
	
		if projections:
			ret['proj'] = projections[0].amount
		else:
			ret['proj'] = Decimal(0.00)
	
		actual = Decimal(0.0)
		for act in actuals:
			actual += act.amount
		ret['actual'] = actual
		if acct.is_income():
			ret['diff'] = ret['actual'] - ret['proj']
		else:
			ret['diff'] = ret['proj'] - ret['actual']
	return ret

def map_categories(categories, month, year, income):
    data = {}
    entries = []
    proj_total = Decimal(0.0)
    act_total = Decimal(0.0)
    for cat in categories:
        entry = {'cat': cat}
        accounts = Account.objects.filter(category=cat)
        all_accounts = []
        proj_subtotal = 0
        act_subtotal = 0
        for acct in accounts:
            data = get_account_amounts_by_date(acct.id, month, year)
            proj_total += data['proj']
            proj_subtotal += data['proj']
            acct_entry = {'acct': acct, 'pred': data['proj'], 'act': data['actual'], 'diff': data['diff']}
            all_accounts.append(acct_entry)
            act_total += data['actual']
            act_subtotal += data['actual']
        entry['accounts'] = all_accounts
        entry['proj_subtotal'] = proj_subtotal
        entry['act_subtotal'] = act_subtotal
        entries.append(entry)
    data['categories'] = entries
    data['act_total'] = act_total
    data['proj_total'] = proj_total
    if income:
        data['difference'] = act_total - proj_total
    else:
        data['difference'] = proj_total - act_total
    return data

def get_goals_context():
    goal_accounts = Account.objects.filter(goal_account=True)
    ret = []
    for acct in goal_accounts:
        info = {}
        info['name'] = acct.name
        info['id'] = acct.id
        info['progress'] = acct.balance
        info['goal'] = acct.goal
        if (acct.goal > 0):
            info['percent'] = int(acct.balance * 100 / acct.goal)
        else:
            info['percent'] = 0
        if info['percent'] > 100:
            info['percent'] = 100
        ret.append(info)
    return ret

def map_bank_balances():
    bank_category = AccountCategory.objects.get(name='Bank Accounts')
    bank_dict = {'cat': bank_category, 'debug': {}, 'accounts': []}
    accts = Account.objects.filter(category=bank_category)
    
    accounts = {}
    subaccounts = []
    accounts_ordered = []
    for acct in accts:
        if not acct.parent_account:
            accounts[acct.id] = acct
            accounts_ordered.append(acct.id)
        else:
            subaccounts.append(acct)
            
    for acct in subaccounts:
        accounts[acct.parent_account.id].balance = accounts[acct.parent_account.id].balance + acct.balance
    
    for aid in accounts_ordered:
        bank_dict['accounts'].append(accounts[aid])
    return bank_dict
    
def index(request, month=None, year=None):
    today = datetime.date.today()
    month_persist = True
    if (not month):
        month = today.strftime('%b')
        month_persist = False
    if (not year):
        year = today.year
        month_persist = False
    prev_month = int(month_abbr_to_int(month, True))
    year_income = year
    if prev_month == 12:
        year_income = int(year) - 1
    month_income = datetime.date(int(year_income), int(prev_month), 1)
    context = {'bank_category': map_bank_balances()}
    context['prev_income_categories'] = map_categories(AccountCategory.objects.filter(income_accounts=True), month_income.strftime('%b'), year_income, True)
    context['income_categories'] = map_categories(AccountCategory.objects.filter(income_accounts=True), month, year, True)
    context['expense_categories'] = map_categories(AccountCategory.objects.filter(income_accounts=False), month, year, False)
    income = {
        'proj': context['income_categories']['proj_total'] - context['income_categories']['categories'][0]['proj_subtotal'] + context['prev_income_categories']['categories'][0]['proj_subtotal'],
        'act': context['income_categories']['act_total'] - context['income_categories']['categories'][0]['act_subtotal'] + context['prev_income_categories']['categories'][0]['act_subtotal']}
    income['difference'] = income['act'] - income['proj']
    context['income'] = income
    context['proj_total'] = income['act'] - context['expense_categories']['proj_total']
    context['act_total'] = income['act'] - context['expense_categories']['act_total']
    context['month'] = month
    context['year'] = year
    context['month_persist'] = month_persist
    context['goals'] = get_goals_context()
    return render(request, 'budget/index.html', context)

def alltransactions(request):
    context = {'transactions': Transaction.objects.filter(prediction=False).order_by('-date')}
    return render(request, 'budget/alltransactions.html', context)
    
def transaction(request, tid, aid):
    trans = get_object_or_404(Transaction, pk=tid)
    context = {}
    context['form'] = TransactionForm()
    context['trans'] = trans
    context['acct'] = get_object_or_404(Account, pk=aid)
    context['category'] = context['acct'].category
    if request.method == 'POST':
        form = TransactionForm(request.POST)
        if form.is_valid():
            old_trans = Transaction.objects.get(id=tid)
            old_amount = trans.amount
            new_trans = form.save(commit = False)
            trans.prediction = False
            if old_trans.from_account.is_income():
                old_trans.from_account.balance = old_trans.from_account.balance - old_amount + new_trans.amount
            else:
                old_trans.from_account.balance = old_trans.from_account.balance + old_amount - new_trans.amount
            old_trans.to_account.balance = old_trans.to_account.balance - old_amount + new_trans.amount
            old_trans.to_account.save()
            old_trans.from_account.save()
            old_trans.amount = new_trans.amount
            old_trans.memo = new_trans.memo
            old_trans.date = form.cleaned_data['date']
            old_trans.save()
            
            return HttpResponseRedirect('/budget/account/'+aid)
    return render(request, 'budget/transaction.html', context)

def account(request, aid, month=None, year=None):
    account = get_object_or_404(Account, pk=aid)
    context = {'account': account, 
               'total_balance': account.balance, 
               'bank': account.category.name == 'Bank Accounts', 
               'can_add_subaccts': not account.parent_account, 
               'subaccounts': Account.objects.filter(parent_account=account.id)
               }
    page = ''
    if account.is_bank() and not account.parent_account:
        page = 'budget/bankaccount.html'
        subaccts = Account.objects.filter(parent_account=account.id)
        for acct in subaccts:
            context['total_balance'] = context['total_balance'] + acct.balance
    else:
        page = 'budget/account.html'
    today = datetime.date.today()
    month_persist = True
    if (not month):
        month = today.strftime('%b')
        month_persist = False
    if (not year):
        year = today.year
        month_persist = False
    context['month'] = month
    context['year'] = year
    context['month_persist'] = month_persist
    dates = start_end_days_of_month(month, year)
    

budget/templates/budget/account.html
{% extends "budget/base.html" %}

{% block breadcrumb %}
	<li><a href="{% url 'budget:alltransactions' %}">All Transactions</a></li>
	<li><a href="{% url 'budget:addtransactions' %}" class="strikethrough">Add Transactions</a></li>
	<li><a href="{% url 'budget:category' account.category.id %}">{{ account.category.name }}</a></li>
	<li class="active"><a href="{% if month_persist %}{% url 'budget:account' account.id month year %}{% else %}{% url 'budget:account' account.id %}{% endif %}">{{ account.name }}</a></li>
{% endblock %}

{% block content %}
	<div class="row">
		<div class="col-xs-9">
			{% if account.goal %}
			<h2>{{ account.name }} Goal</h2>
			<p>${{ account.goal }}</p>
			{% endif %}
			<h2>Transactions for {{ account.name }}</h2>
			<br />
			<table class="table">
			<tr><th>Date</th><th>Account</th><th>Deposit</th><th>Withdrawal</th><th>Memo</th><th>Edit</th></tr>
			{% for t in transactions %}
				<tr><td>{{ t.date }}</td>
				{% if t.to_account|cut:" " == account.name|cut:" " %}
					<td><a href="{% url 'budget:account' t.from_account.id %}">{{ t.from_account }}</a></td><td>${{ t.amount }}</td><td></td>
				{% else %}
					<td><a href="{% url 'budget:account' t.to_account.id %}">{{ t.to_account }}</a></td><td></td><td>${{ t.amount }}</td>
				{% endif %}
				<td>{{ t.memo }}</td>
				<td><a href="{% url 'budget:transaction' t.id account.id %}">Edit</a></td></tr>
			{% endfor %}
			<tr><td></td><td><strong>Monthly Balance:</strong></td><td>${{ balance }}</td><td colspan="3"></td></tr>
			<tr><td></td><td><strong>Overall Balance:</strong></td><td>${{ account.balance }}</td><td colspan="3"></td></tr>
			</table>
		</div>
		<div class="col-xs-3 text-center">
			<div class="row">
				<div class="col-xs-12">
					<h3>Select Date</h3>
					{% include "budget/month_selection.html" %}
				</div>
			</div>
			<br />
			<div class="row">
				<div class="col-xs-12">
					{% if bank %}
						<a href="{% url 'budget:banktransaction' %}" class="btn btn-success">Transfer Funds</a>
					{% else %}
						<a href="{% url 'budget:addtransaction' account.id %}" class="btn btn-success">Add New Transaction</a>
					{% endif %}
				</div>
			</div>
			<br />
			{% if bank and can_add_subaccts %}
			<div class="row">
				<div class="col-xs-12">
					<a href="{% url 'budget:addsubaccount' account.id %}" class="btn btn-info">Add Sub-account</a>
				</div>
			</div>
			<br />
			{% endif %}
			<div class="row">
				<div class="col-xs-12">
					<a href="{% url 'budget:editaccount' account.id %}" class="btn btn-warning">Edit Account</a>
				</div>
			</div>
			<br />
			<div class="row">
				<div class="col-xs-12">
					<a href="{% url 'budget:deleteaccount' account.id %}" class="btn btn-danger">Delete Account</a>
				</div>
			</div>
			<br />
		</div>
	</div>
{% endblock %}

{% block javascript %}
	<script src="/static/budget/js/month_selection.js" type="text/javascript"></script>
{% endblock %}

budget/templates/budget/adddeposit.html
{% extends "budget/base.html" %}

{% block breadcrumb %}
	<li><a href="{% url 'budget:category' account.category.id %}">{{ account.category.name }}</a></li>
	<li><a href="{% url 'budget:account' account.id %}">{{ account.name }}</a></li>
{% endblock %}

{% block content %}
	<div class="row">
		<div class="col-xs-12">
			<h2>New Deposit under {{ account }}</h2>
			<br /><br />
		</div>
	</div>
	<div class="row">
		<div class="col-xs-3">
			{% if error_message %}<p>{{ error_message }}</p>{% endif %}
			<form role="form" action="{% url 'budget:addtransaction' account.id %}" method="post">
				{% csrf_token %}
				<div class="form-group">
					<label for="id_date">Date:</label>
					{{ form.date }}
				</div>
				<div class="form-group">
					<label for="id_from_account">Deposit into:</label>
					{{ form.from_account }}
				</div>
				<div class="form-group">
					<label for="id_amount">Amount Deposited:</label>
					{# Mimics {{ form.amount }}, but done manually to add class to input #}
					<input id="id_amount" type="number" step="0.01" name="amount" class="form-control">
				</div>
				<div class="form-group">
					<label for="id_memo">Memo:</label>
					
					<input id="id_memo" type="text" name="memo" maxlength="300" class="form-control">
				</div>
				<div class="form-group">
					<input type="submit" class="btn btn-primary" value="Save" />
				</div>
			</form>
		</div>
	</div>
{% endblock %}

{% block javascript %}
	<script src="/static/budget/js/transaction.js" type="text/javascript" ></script>
{% endblock %}

budget/templates/budget/addsubaccount.html
{% extends "budget/base.html" %}

{% block breadcrumb %}
	<li><a href="{% url 'budget:category' category.id %}">{{ category.name }}</a></li>
	<li><a href="{% url 'budget:account' parent_account.id %}">{{ parent_account.name }}</a></li>
{% endblock %}

{% block content %}
	<div class="row">
		<div class="col-xs-12">
			<h2>New Sub-Account Under {{ parent_account.name }}</h2>
			<br /><br />
		</div>
	</div>
	<div class="row">
		<div class="col-xs-3">
			{% if error_message %}<p>{{ error_message }}</p>{% endif %}
			<form role="form" action="{% url 'budget:addsubaccount' parent_account.id %}" method="post">
				{% csrf_token %}
				<div class="form-group">
					<label for="id_name">Name:</label>
					<input type="text" name="name" maxlength="200" id="id_name" class="form-control">
				</div>
				<div class="form-group">
					<label for="id_balance">Starting Balance:</label> 
					<input type="number" step="0.01" name="balance" id="id_balance" class="form-control" value="0.00">
				</div>
				<input type="hidden" name="parent_account" value="{{ parent_account.id }}">
				<input type="hidden" name="category" value="{{ category }}">
				<div class="checkbox">
					<label> 
						<input type="checkbox" name="goal_account" id="id_goal_account" checked="checked"> Will this be a goal account?
					</label>
				</div>
				<div class="form-group">
					<label for="id_goal">Goal:</label> 
					<input type="number" step="0.01" name="goal" id="id_goal" class="form-control" value="0">
				</div>
				<div class="form-group">
					<input type="submit" class="btn btn-primary" value="Save" />
				</div>
			</form>
		</div>
	</div>
{% endblock %}

{% block javascript %}
	<script type="text/javascript">
		jQuery(function($){
			$('#id_goal_account').click(function(){
				if ($(this).prop('checked') == true){
					$('#id_goal').prop('disabled', false);
				}
				else{
					$('#id_goal').val(0);
					$('#id_goal').prop('disabled', true);
				}
			});
		});
	</script>
{% endblock %}

budget/templates/budget/bankaccount.html
{% extends "budget/base.html" %}

{% block breadcrumb %}
	<li><a href="{% url 'budget:alltransactions' %}">All Transactions</a></li>
	<li><a href="{% url 'budget:addtransactions' %}" class="strikethrough">Add Transactions</a></li>
	<li><a href="{% url 'budget:category' account.category.id %}">{{ account.category.name }}</a></li>
	<li class="active"><a href="{% if month_persist %}{% url 'budget:account' account.id month year %}{% else %}{% url 'budget:account' account.id %}{% endif %}">{{ account.name }}</a></li>
{% endblock %}

{% block content %}
	<div class="row">
		<div class="col-xs-9">
            <h2>Fund Allocation</h2>
            <br />
            <table class="table">
            <tr><th>Account</th><th>Current Allocation</th></tr>
            {% for sub in subaccounts %}
            <tr><td><a href="{% url 'budget:account' sub.id %}">{{ sub.name }}</td><td>${{ sub.balance }}</td></tr>
            {% endfor %}
            <tr><td><strong>Unallocated Balance:</strong></td><td>${{ account.balance }}</td>
            <tr><td><strong>Total Balance:</strong></td><td>${{ total_balance }}</td>
            </table>
        
			<h2>Transfers for {{ account.name }}</h2>
			<br />
			<table class="table">
			<tr><th>Date</th><th>Account</th><th>Deposit</th><th>Withdrawal</th><th>Memo</th><th>Edit</th></tr>
			{% for t in transactions %}
				<tr><td>{{ t.date }}</td>
				{% if t.to_account|cut:" " == account.name|cut:" " %}
					<td><a href="{% url 'budget:account' t.from_account.id %}">{{ t.from_account }}</a></td><td>${{ t.amount }}</td><td></td>
				{% else %}
					<td><a href="{% url 'budget:account' t.to_account.id %}">{{ t.to_account }}</a></td><td></td><td>${{ t.amount }}</td>
				{% endif %}
				<td>{{ t.memo }}</td>
				<td><a href="{% url 'budget:transaction' t.id account.id %}">Edit</a></td></tr>
			{% endfor %}
			<tr><td></td><td><strong>Monthly Balance:</strong></td><td>${{ balance }}</td><td colspan="3"></td></tr>
            </table>
		</div>
		<div class="col-xs-3 text-center">
			<div class="row">
				<div class="col-xs-12">
					<h3>Select Date</h3>
					{% include "budget/month_selection.html" %}
				</div>
			</div>
			<br />
			<div class="row">
				<div class="col-xs-12">
					{% if bank %}
						<a href="{% url 'budget:banktransaction' %}" class="btn btn-success">Transfer Funds</a>
					{% else %}
						<a href="{% url 'budget:addtransaction' account.id %}" class="btn btn-success">Add New Transaction</a>
					{% endif %}
				</div>
			</div>
			<br />
			{% if bank %}
			<div class="row">
				<div class="col-xs-12">
					<a href="{% url 'budget:addsubaccount' account.id %}" class="btn btn-info">Add Sub-account</a>
				</div>
			</div>
			<br />
			{% endif %}
			<div class="row">
				<div class="col-xs-12">
					<a href="{% url 'budget:editaccount' account.id %}" class="btn btn-warning">Edit Account</a>
				</div>
			</div>
			<br />
		</div>
	</div>
{% endblock %}

{% block javascript %}
	<script src="/static/budget/js/month_selection.js" type="text/javascript"></script>
{% endblock %}

budget/templates/budget/editaccount.html
{% extends "budget/base.html" %}

{% block breadcrumb %}
	<li><a href="{% url 'budget:category' category.id %}">{{ category.name }}</a></li>
	<li class="active"><a href="{% url 'budget:account' account.id %}">{{ account.name }}</a></li>
{% endblock %}

{% block content %}
	<div class="row">
		<div class="col-xs-12">
			<h2>Edit "{{ account.name }}" Account</h2>
			<br /><br />
		</div>
	</div>
	{% if error %}
	<div class="row">
		<div class="col-xs-12 error">
			{{ error }}
		</div>
	</div>
	{% endif %}
	<div class="row">
		<div class="col-xs-3">
			{% if error %}<p>{{ error }}</p>{% endif %}
			<form role="form" action="{% url 'budget:editaccount' account.id %}" method="post">
				{% csrf_token %}
				<div class="form-group">
					<label for="id_name">Name:</label>
					<input type="text" name="name" maxlength="200" id="id_name" class="form-control" value="{{ account.name }}">
				</div>
				<div class="form-group">
					<label for="id_category">Category:</label>
					{{ form.category }}
				</div>
				<div class="form-group">
					<label for="id_parent_account">Make this account a subset of </label>
					{{ form.parent_account }}
				</div>
				<div class="form-group">
					<label for="id_balance">Current Balance ($):</label>
					<input id="id_balance" type="number" step="0.01" name="balance" class="form-control" value="{{ account.balance }}">
				</div>
				<div class="checkbox">
					<label> 
						{{ form.goal_account }} Will this be a goal account?
					</label>
				</div>
				<div class="form-group">
					<label for="id_goal">End Goal ($):</label> 
					<input type="number" step="0.01" name="goal" id="id_goal" class="form-control" value="{{ account.goal }}">
				</div>
				<div class="form-group">
					<input type="submit" class="btn btn-primary" value="Save" />
				</div>
			</form>
		</div>
	</div>
{% endblock %}

{% block javascript %}
	<script type="text/javascript">
		jQuery(function($){
			$('#id_goal_account').click(function(){
				if ($(this).prop('checked') == true){
					$('#id_goal').prop('disabled', false);
				}
				else{
					$('#id_goal').val(0);
					$('#id_goal').prop('disabled', true);
				}
			});
			
			$('#id_category').click(function(){
				if ($(this).val() == 2){
					$('#id_parent_account').prop('disabled', false);
				}
				else{
					$('#id_parent_account').val('');
					$('#id_parent_account').prop('disabled', true);
				}
			});
			
			$('#id_category').trigger('click');
		});
	</script>
{% endblock %}